name: Build and Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Generate
        run: npm run generate
      - name: Tar dist
        run: mkdir pkg && tar -cvf pkg/nuxt3-ts-tailwindui.tar.gz ./.output/public
      - name: Deploy to Compute@Edge
        uses: fastly/compute-actions@v5
        env:
          FASTLY_API_TOKEN: ${{ secrets.FASTLY_TOKEN }}
